// Generated by CoffeeScript 1.6.3
(function() {
  var count, div, fs, mid, num, out, outfile, prime, x, _i, _len;

  fs = require('fs');

  prime = [];

  count = 100;

  num = 2;

  while (prime.length !== count) {
    mid = Math.sqrt(num);
    div = 0;
    for (_i = 0, _len = prime.length; _i < _len; _i++) {
      x = prime[_i];
      if (x <= mid && x > 1) {
        if (num % x === 0) {
          div = x;
          break;
        }
      }
    }
    if (div === 0) {
      prime.push(num);
    }
    num++;
  }

  outfile = 'part-02-content.txt';

  out = prime.join();

  console.log(out);

  fs.writeFile(outfile, out, function(err) {
    if (err) {
      return console.log('write file error :' + err);
    } else {
      return console.log('execute successfully');
    }
  });

}).call(this);
