// Generated by CoffeeScript 1.6.3
(function() {
  var fs, out, outfile;

  fs = require('fs');

  outfile = 'part-01-content.txt';

  out = 'A startup is a business built to grow rapidly.\n';

  fs.writeFile(outfile, out, function(err) {
    if (err) {
      return console.log('file write err : ' + err);
    } else {
      return console.log("Script: " + __filename + "\nWrote: " + out + "To: " + outfile);
    }
  });

}).call(this);
